export const MenuCategory = [
    {
        id: 1,
        name: 'فرانت اند',
        category: 'frontend',
        submenu: [
            { id: 1, name: 'آموزش HTML' },
            { id: 2, name: 'آموزش CSS' },
            { id: 3, name: 'آموزش FlexBox' },
            { id: 4, name: 'آموزش Tailwind CSS' },
            { id: 5, name: 'آموزش بوت استرپ' },
            { id: 6, name: 'آموزش جاوااسکریپت' },
            { id: 7, name: 'پروژه های تخصصی با JS' },
            { id: 8, name: 'آموزش جامع ری اکت ReactJS' },
        ]
    },
    {
        id: 2,
        name: 'امنیت',
        category: 'securty',
        submenu: [
            { id: 1, name: 'شبکه با گرایش امنیت' },
            { id: 2, name: 'لینوکس با گرایش امنیت' },
            { id: 3, name: 'آموزش هکر قانونمند - CEH V11' },
            { id: 4, name: 'آموزش کالی لینوکس' },
            { id: 5, name: 'آموزش پایتون سیاه' },
            { id: 6, name: 'آموزش Burp Suite' },
            { id: 7, name: 'آموزش جاوااسکریپت سیاه' },
        ]
    },
    {
        id: 3,
        name: 'پایتون',
        category: 'payton',
        submenu: [
            { id: 1, name: 'دوره آموزش پایتون' },
            { id: 2, name: 'پروژه های کاربردی با پایتون' },
            { id: 3, name: 'بهینه نویسی کد ها در پایتون' },
            { id: 4, name: 'متخصص جنگو' },
            { id: 5, name: 'متخصص جنگو' },
            { id: 6, name: 'مصور سازی داده با پایتون' },
        ]
    },
    {
        id: 4,
        name: 'پی اچ پی',
        category: 'php',
        submenu: [
            { id: 1, name: 'ربات تلگرام با PHP' },
            { id: 2, name: 'پروژه های کاربردی با PHP' },
        ]
    },
    {
        id: 5,
        name: 'ارتقای مهارت',
        category: 'softSkills',
        submenu: [
            { id: 1, name: 'الگوریتم و ساختمان داده' },
            { id: 2, name: 'آموزش websocket' },
            { id: 3, name: 'گیت و گیتهاب' },
            { id: 4, name: 'آموزش GraphQL' },
            { id: 5, name: 'توسعه کتابخانه با JS' },
            { id: 6, name: 'افزونه نویسی با JS' },
            { id: 7, name: 'Clean Code برای JS' },
            { id: 8, name: 'دیپلوی پروژه های JS' },
            { id: 9, name: 'دوره Mern Stack' },
        ]
    },
    {
        id: 6,
        name: 'مقالات',
        category: 'articles',
        submenu: [
            { id: 1, name: 'اچ تی ام ال' },
            { id: 2, name: 'بوت استرپ' },
            { id: 3, name: 'تست نفوذ و امنیت وب' },
            { id: 4, name: 'ری اکت جی اس' },
            { id: 5, name: 'سی اس اس' },
            { id: 6, name: 'طراحی سایت' },
        ]
    },
]



export const Courses = [
    {
        id: 1,
        title: 'آموزش جامع api نویسی با PHP',
        subtitle: 'API یکی از پر کاربردترین اجزای نرم افزاریه که حتما باید بلد باشی! توی این دوره قراره api',
        teacher: 'معین باغشیخی',
        price: '950,000',
        student: 44,
        img: './images/courses/php-1.webp',
    },
    {
        id: 2,
        title: 'آموزش Docker از صفر مطلق!',
        subtitle: 'داکر یک پلتفرم متن باز برای طراحی؛ انتقال؛ استقرار و اجرای نرم افزار ها تحت مفهومی به',
        teacher: 'آرمین هوشمند',
        price: '1,499,000 ',
        student: 60,
        img: './images/courses/Docker.webp',
    },
    {
        id: 3,
        title: 'آموزش پروژه محور WebSocket',
        subtitle: 'با Socket می‌تونی مثل تلگرام یا سایت های ارز دیجیتال یه ارتباط Realtime بسازی و بدون نیاز به ارسال یه…',
        teacher: 'محمدامین سعیدی راد',
        price: '1,190,000',
        student: 253,
        img: './images/courses/websocket.webp',
    },
    {
        id: 4,
        title: 'توسعه کتابخانه با جاوااسکریپت',
        subtitle: 'توسعه کتابخانه، نمونه کاری قوی برای رزومه شما است و این دوره آموزشی یادگیری چنین',
        teacher: 'مهرشاد براتی',
        price: '1,300,000 ',
        student: 78,
        img: './images/courses/js-1.webp',
    },
    {
        id: 5,
        title: 'پروژه های کاربردی با PHP',
        subtitle: '"مینی پروژه‌های کاربری با PHP" یه دوره آموزشی گام به گام هست که برای توسعه‌دهندگان وب،',
        teacher: 'معین باغشیخی',
        price: 'رایگان!',
        student: 11089,
        img: './images/courses/php-2.webp',
    },
    {
        id: 6,
        title: 'آموزش ساخت ربات تلگرام با PHP',
        subtitle: 'توی دوره فوق‌العاده جذاب و کاربردی ساخت ربات تلگرام با php، به دنیای عجیب و جذاب',
        teacher: 'معین باغشیخی',
        price: '670,000',
        student: 288,
        img: './images/courses/php-3.webp',
    },
    {
        id: 7,
        title: 'دوره کاربردی chatGPT برای برنامه نویس ها',
        subtitle: 'هوش مصنوعی داره جهان رو در بر میگیره و به سرعت درحال پیشرفته و همین پیشرفتش',
        teacher: 'قدیر یلمه',
        price: 'رایگان!',
        student: 16606,
        img: './images/courses/chatgpt.webp',
    },
    {
        id: 8,
        title: 'آموزش جامع و پروژه محور Tailwind css',
        subtitle: 'tailwind css یک فریمورک Utility First هست، این فریمورک متشکل از یکسری کلاس های',
        teacher: 'حمیدرضا عبادی',
        price: '780,000',
        student: 1378,
        img: './images/courses/tailwind.webp',
    },
    {
        id: 9,
        title: 'آموزش git و github',
        subtitle: 'گیت یه Version Controller هست که نسخه های مختلف پروژه هامون رو مدیریت و نگهداری',
        teacher: 'محمدامین سعیدی راد',
        price: '690,000',
        student: 1288,
        img: './images/courses/git.webp',
    },
    {
        id: 10,
        title: 'آموزش کاربردی Typescript بصورت پروژه محور',
        subtitle: 'تایپ اسکریپت یه زبون برنامه نویسیه که توسط مایکروسافت ارائه شده و یسری قابلیت و فیچ',
        teacher: 'محمدامین سعیدی راد',
        price: '2,399,000 ',
        student: 503,
        img: './images/courses/type.webp',
    },
    {
        id: 11,
        title: 'آموزش حرفه ای NodeJS بدون پیش نیاز',
        subtitle: 'الان و امروز کمتر کسی هست که از بازار کار داغ نود جی اس با خبر نباشه و یکی از',
        teacher: 'محمدامین سعیدی راد',
        price: '4,350,000',
        student: '549',
        img: './images/courses/node.webp',
    },
    {
        id: 12,
        title: 'Api نویسی با Nodejs',
        subtitle: 'شما بعد از گذروندن این دوره میتونین واسه پروژه هایی که تو زمینه فرانت‌اند توسعه',
        teacher: 'محمدامین سعیدی راد',
        price: '870,000',
        student: '474',
        img: './images/courses/node-1.webp',
    },
    {
        id: 13,
        title: 'دوره هکرقانونمند با دیدگاهی متفاوت و تجربی | CEH V11',
        subtitle: 'یکی از دوره هایی که در مسیر یادگیری هک و امنیت باید بهش مراجعه کنید. دوره CEH',
        teacher: 'اشکان مقدس',
        price: '2,300,000',
        student: 771,
        img: './images/courses/haker.webp',
    },
    {
        id: 14,
        title: 'آموزش ری اکت ( ReactJS ) در دنیای واقعی | از 0 تا استخدام [منتورشیپ]',
        subtitle: 'حدود 40 ساعت آموزش جامع و تخصصی ری اکت!  شما در دوره آموزش ری اکت ReactJS',
        teacher: 'محمدامین سعیدی راد',
        price: '4,800,000 ',
        student: 1847,
        img: './images/courses/react.webp',
    },
    {
        id: 15,
        title: 'آموزش پایتون رایگان مقدماتی تا پیشرفته + پروژه های جذاب',
        subtitle: 'حیف نیست محبوب ترین زبان برنامه نویسی دنیا رو  ناقص و بی هدف یادبگیری؟ ما تصمی',
        teacher: 'رضا دولتی',
        price: 'رایگان!',
        student: 77109,
        img: './images/courses/payton.webp',
    },
]


export const articles = [
    {
        id: 1,
        title: 'Vue JS چیست ؟',
        subTitle: 'یکی از بخش‌های مهم در توسعه یک پروژه، نحوه تعامل کاربران با پروژه است؛ جایی که اهمیت طراحی رابط کاربری یا UI Design بیشتر به چشم می‌آید. در توسعه وب،',
        img: './images/articles/article-1.webp',
    },
    {
        id: 2,
        title: 'css چیست و چه کاربردی دارد؟',
        subTitle: 'در دنیای وب، به نظر می‌رسد همه چیز بر اساس زیبایی و قدرت گرافیکی استوار است. اما آیا همه آن زیبایی و جذابیت که در هر وب‌سایت دیده می‌شود، صرفاً',
        img: './images/articles/article-2.webp',
    },
    {
        id: 3,
        title: 'پیش نیازهای یادگیری جاوا اسکریپت',
        subTitle: 'بدون شک، یادگیری زبان جاوا اسکریپت یکی از اساسی‌ترین مراحل در مسیر توسعه وب است. این زبان برنامه‌نویسی پویا، که از طریق مرورگرهای اینترنتی اجرا می‌شود، امروزه بخش',
        img: './images/articles/article-3.webp',
    },
    {
        id: 4,
        title: 'آموزش Eval در جاوا اسکریپت',
        subTitle: 'تابع eval در جاوا اسکریپت نوعی تابع داخلی است که می‌توان به صورت سراسری به آن دسترسی داشت، به این معنی که شما به عنوان یک برنامه‌نویس می‌توانید بدون نیاز ',
        img: './images/articles/article-4.webp',
    },
]